### ISSUE TITLE
Neue Erkenntnisse: Github vs. Gitlab

### ISSUE THREAD

**Issue by SarahThomsen** [sierrahamburg/weltherrschaft#1]
Hallo @mtypke ,

vielleicht war Dir dieser Unterschied ja schon immer klar, aber Github und Gitlab sind mehr oder weniger dasselbe. Ich dachte ja immer, Github ist die Versionskontrolle und Gitlab der dazugehörige Issuetracker. 

Stimmt aber nicht. Beide können beides. Der Unterschied zwischen Gitlab und Github ist, dass Github gehostet wird und entweder öffentlich ist oder man was zahlen muss. Gitlab ist opensource und muss auf dem eigenen Server installiert werden.

Für IP nutzen wir Gitlab. Das müsstest dann aber Du einrichten, bei dem ganzen Linux-Server-Gedöns bin ich raus: https://about.gitlab.com/installation/

Wat meinste?

Viele Grüße,
Sarah

**Comment by mtypke** [comment]
Hallo Sarah,

ich muss mir das für den Server in Ruhe ansehen. Anscheinend drückt einem das Standard- Installationspaket einen anderen Webserver als Apache aufs Auge. 

Auf dem Testsystem läuft auch die Anwendung für meinen Lieblingskunden… Daher kann ich da nicht zu viel rumexperimentieren.
